# Generated by Django 4.1.5 on 2023-01-30 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=200)),
                ('int_field', models.IntegerField(default=1)),
                ('date_field', models.DateField(default=datetime.date(2023, 1, 30))),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
